package schema

type Column struct {
	Name          string
	Type          string
	DBType        string
	Default       string
	Comment       string
	Nullable      bool
	Unique        bool
	Validated     bool
	AutoGenerated bool
	ArrType       *string
	UDTName       string
	DomainName    *string
	FullDBType    string
}

func ColumnNames(cols []Column) []string {
	names := make([]string, len(cols))
	for i, c := range cols {
		names[i] = c.Name
	}
	return names
}

func ColumnDBTypes(cols []Column) map[string]string {
	m := make(map[string]string, len(cols))
	for _, c := range cols {
		m[c.Name] = c.DBType
	}
	return m
}

func FilterColumnsByAuto(auto bool, columns []Column) []Column {
	var result []Column
	for _, c := range columns {
		if c.AutoGenerated == auto {
			result = append(result, c)
		}
	}
	return result
}

func FilterColumnsByDefault(hasDefault bool, columns []Column) []Column {
	var result []Column
	for _, c := range columns {
		if hasDefault && c.Default != "" {
			result = append(result, c)
		} else if !hasDefault && c.Default == "" {
			result = append(result, c)
		}
	}
	return result
}

func FilterColumnsByEnum(columns []Column) []Column {
	var result []Column
	for _, c := range columns {
		if IsEnumDBType(c.DBType) {
			result = append(result, c)
		}
	}
	return result
}

func IsEnumDBType(dbType string) bool {
	return len(dbType) > 5 && dbType[:4] == "enum" && dbType[4] == '('
}
