package schema

import (
	"testing"
)

func TestColumnNames(t *testing.T) {
	cols := []Column{{Name: "id"}, {Name: "name"}, {Name: "age"}}
	names := ColumnNames(cols)
	if len(names) != 3 || names[0] != "id" || names[1] != "name" || names[2] != "age" {
		t.Errorf("unexpected names: %v", names)
	}
}

func TestColumnDBTypes(t *testing.T) {
	cols := []Column{{Name: "id", DBType: "integer"}, {Name: "name", DBType: "varchar"}}
	types := ColumnDBTypes(cols)
	if types["id"] != "integer" || types["name"] != "varchar" {
		t.Errorf("unexpected types: %v", types)
	}
}

func TestFilterColumnsByAuto(t *testing.T) {
	cols := []Column{
		{Name: "id", AutoGenerated: true},
		{Name: "name", AutoGenerated: false},
		{Name: "created_at", AutoGenerated: true},
	}
	auto := FilterColumnsByAuto(true, cols)
	if len(auto) != 2 {
		t.Errorf("expected 2 auto columns, got %d", len(auto))
	}
	notAuto := FilterColumnsByAuto(false, cols)
	if len(notAuto) != 1 || notAuto[0].Name != "name" {
		t.Errorf("expected 1 non-auto column, got %v", notAuto)
	}
}

func TestFilterColumnsByDefault(t *testing.T) {
	cols := []Column{
		{Name: "id", Default: "nextval('seq')"},
		{Name: "name"},
		{Name: "status", Default: "'active'"},
	}
	withDefault := FilterColumnsByDefault(true, cols)
	if len(withDefault) != 2 {
		t.Errorf("expected 2 default columns, got %d", len(withDefault))
	}
	noDefault := FilterColumnsByDefault(false, cols)
	if len(noDefault) != 1 || noDefault[0].Name != "name" {
		t.Errorf("expected 1 no-default column, got %v", noDefault)
	}
}

func TestFilterColumnsByEnum(t *testing.T) {
	cols := []Column{
		{Name: "status", DBType: "enum('active','inactive')"},
		{Name: "name", DBType: "varchar"},
	}
	enums := FilterColumnsByEnum(cols)
	if len(enums) != 1 || enums[0].Name != "status" {
		t.Errorf("expected 1 enum column, got %v", enums)
	}
}

func TestIsEnumDBType(t *testing.T) {
	tests := []struct {
		input string
		want  bool
	}{
		{"enum('a','b')", true},
		{"varchar", false},
		{"integer", false},
		{"enum", false},
		{"enumx", false},
	}
	for _, tt := range tests {
		got := IsEnumDBType(tt.input)
		if got != tt.want {
			t.Errorf("IsEnumDBType(%q) = %v, want %v", tt.input, got, tt.want)
		}
	}
}

func TestGetTable(t *testing.T) {
	tables := []Table{{Name: "users"}, {Name: "orders"}}
	tbl := GetTable(tables, "orders")
	if tbl.Name != "orders" {
		t.Errorf("expected orders, got %s", tbl.Name)
	}
}

func TestGetTablePanics(t *testing.T) {
	defer func() {
		if r := recover(); r == nil {
			t.Error("expected panic for missing table")
		}
	}()
	GetTable([]Table{{Name: "users"}}, "missing")
}

func TestTableGetColumn(t *testing.T) {
	tbl := Table{Columns: []Column{{Name: "id"}, {Name: "name"}}}
	col := tbl.GetColumn("name")
	if col.Name != "name" {
		t.Errorf("expected name, got %s", col.Name)
	}
}

func TestCanLastInsertID(t *testing.T) {
	tbl := Table{
		PKey:    &PrimaryKey{Columns: []string{"id"}},
		Columns: []Column{{Name: "id", Type: "int64", Default: "auto"}},
	}
	if !tbl.CanLastInsertID() {
		t.Error("should be able to use last insert id")
	}

	tbl2 := Table{
		PKey:    &PrimaryKey{Columns: []string{"id"}},
		Columns: []Column{{Name: "id", Type: "string", Default: "uuid()"}},
	}
	if tbl2.CanLastInsertID() {
		t.Error("string PK should not support last insert id")
	}
}

func TestCanSoftDelete(t *testing.T) {
	tbl := Table{
		Columns: []Column{
			{Name: "deleted_at", Type: "null.Time", Nullable: true},
		},
	}
	if !tbl.CanSoftDelete("deleted_at") {
		t.Error("should support soft delete")
	}
	if tbl.CanSoftDelete("removed_at") {
		t.Error("should not support soft delete for nonexistent column")
	}
}

func TestSQLColumnDefs(t *testing.T) {
	cols := []Column{{Name: "id", Type: "int"}, {Name: "name", Type: "string"}}
	defs := MakeSQLColumnDefs(cols, []string{"id", "name"})
	names := defs.Names()
	types := defs.Types()
	if len(names) != 2 || names[0] != "id" || names[1] != "name" {
		t.Errorf("unexpected names: %v", names)
	}
	if types[0] != "int" || types[1] != "string" {
		t.Errorf("unexpected types: %v", types)
	}
}

func TestDetectToOneRelationships(t *testing.T) {
	tables := []Table{
		{Name: "users", PKey: &PrimaryKey{Columns: []string{"id"}}},
		{
			Name: "profiles",
			FKeys: []ForeignKey{
				{Table: "profiles", Column: "user_id", ForeignTable: "users", ForeignColumn: "id", Unique: true},
			},
		},
	}
	rels := DetectToOneRelationships("users", tables)
	if len(rels) != 1 {
		t.Fatalf("expected 1 to-one relationship, got %d", len(rels))
	}
	if rels[0].ForeignTable != "profiles" {
		t.Errorf("expected foreign table 'profiles', got %q", rels[0].ForeignTable)
	}
}

func TestDetectToManyRelationships(t *testing.T) {
	tables := []Table{
		{Name: "users", PKey: &PrimaryKey{Columns: []string{"id"}}},
		{
			Name: "orders",
			FKeys: []ForeignKey{
				{Table: "orders", Column: "user_id", ForeignTable: "users", ForeignColumn: "id", Unique: false},
			},
		},
	}
	rels := DetectToManyRelationships("users", tables)
	if len(rels) != 1 {
		t.Fatalf("expected 1 to-many relationship, got %d", len(rels))
	}
	if rels[0].ForeignTable != "orders" {
		t.Errorf("expected foreign table 'orders', got %q", rels[0].ForeignTable)
	}
}

func TestDetectManyToManyRelationships(t *testing.T) {
	tables := []Table{
		{Name: "users", PKey: &PrimaryKey{Columns: []string{"id"}}},
		{Name: "tags", PKey: &PrimaryKey{Columns: []string{"id"}}},
		{
			Name:        "user_tags",
			IsJoinTable: true,
			PKey:        &PrimaryKey{Columns: []string{"user_id", "tag_id"}},
			FKeys: []ForeignKey{
				{Table: "user_tags", Column: "user_id", ForeignTable: "users", ForeignColumn: "id"},
				{Table: "user_tags", Column: "tag_id", ForeignTable: "tags", ForeignColumn: "id"},
			},
		},
	}
	rels := DetectToManyRelationships("users", tables)
	if len(rels) != 1 {
		t.Fatalf("expected 1 many-to-many relationship, got %d", len(rels))
	}
	if !rels[0].ToJoinTable {
		t.Error("expected ToJoinTable to be true")
	}
	if rels[0].JoinTable != "user_tags" {
		t.Errorf("expected join table 'user_tags', got %q", rels[0].JoinTable)
	}
	if rels[0].ForeignTable != "tags" {
		t.Errorf("expected foreign table 'tags', got %q", rels[0].ForeignTable)
	}
}

func TestConfigMustString(t *testing.T) {
	c := Config{"host": "localhost"}
	if c.MustString("host") != "localhost" {
		t.Error("MustString should return the value")
	}
}

func TestConfigMustStringPanics(t *testing.T) {
	defer func() {
		if r := recover(); r == nil {
			t.Error("expected panic for missing key")
		}
	}()
	c := Config{}
	c.MustString("missing")
}

func TestConfigDefaultString(t *testing.T) {
	c := Config{"host": "localhost"}
	if c.DefaultString("host", "default") != "localhost" {
		t.Error("should return existing value")
	}
	if c.DefaultString("missing", "fallback") != "fallback" {
		t.Error("should return default for missing key")
	}
}

func TestConfigInt(t *testing.T) {
	c := Config{"port": float64(5432)}
	n, ok := c.Int("port")
	if !ok || n != 5432 {
		t.Errorf("expected 5432, got %d (ok=%v)", n, ok)
	}
}

func TestConfigDefaultBool(t *testing.T) {
	c := Config{"debug": true}
	if !c.DefaultBool("debug", false) {
		t.Error("should return true")
	}
	if c.DefaultBool("missing", false) {
		t.Error("should return false default")
	}
}

func TestConfigStringSlice(t *testing.T) {
	c := Config{"tables": []any{"users", "orders"}}
	s, ok := c.StringSlice("tables")
	if !ok || len(s) != 2 {
		t.Errorf("expected 2 items, got %v (ok=%v)", s, ok)
	}
}

func TestTablesFromList(t *testing.T) {
	list := []string{"users", "orders", "users.name", "orders.id"}
	tables := TablesFromList(list)
	if len(tables) != 2 {
		t.Errorf("expected 2 tables, got %v", tables)
	}
}

func TestColumnsFromList(t *testing.T) {
	list := []string{"users.name", "users.age", "orders.id", "*.created_at"}
	cols := ColumnsFromList(list, "users")
	if len(cols) != 3 {
		t.Errorf("expected 3 columns for users (name, age, created_at), got %v", cols)
	}
}

func TestDriverRegistration(t *testing.T) {
	d := &mockDriver{}
	RegisterDriver("mock_test", d)
	got := GetDriver("mock_test")
	if got != d {
		t.Error("GetDriver should return the registered driver")
	}
}

func TestGetDriverPanics(t *testing.T) {
	defer func() {
		if r := recover(); r == nil {
			t.Error("expected panic for unregistered driver")
		}
	}()
	GetDriver("nonexistent_driver_xyz")
}

type mockDriver struct{}

func (m *mockDriver) Assemble(config Config) (*DBInfo, error) { return nil, nil }
func (m *mockDriver) Templates() (map[string]string, error)   { return nil, nil }
func (m *mockDriver) Imports() (map[string]any, error)         { return nil, nil }
